### ISSUE TITLE
broker history: Error: collection name must be a String

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#66]
I have the following issue when trying the broker history.
First I start Orion/Mongo/Cygnus with the instructions in: https://github.com/Waziup/Platform/blob/master/broker/broker_test.md

Then run broker history: 
```
docker run -t --net=host waziup/brokerhistory
```
Perform a request:
```
curl -S -s http://127.0.0.1:8081/?id=583eecac2ab79c00079d0579&colName=sth_/TEST_Sensor1_SensingDevice&dbName=sth_waziupdb
```
Result is:
```
Server listening at http://:::8080
Got a GET request for ... 
Connection established to mongodb://localhost:27017/undefined
/usr/src/app/node_modules/mongodb/lib/mongo_client.js:236
          throw err
          ^

Error: collection name must be a String
    at Error (native)
    at checkCollectionName (/usr/src/app/node_modules/mongodb/lib/utils.js:69:11)
    at new Collection (/usr/src/app/node_modules/mongodb/lib/collection.js:60:3)
    at Db.collection (/usr/src/app/node_modules/mongodb/lib/db.js:453:24)
    at /usr/src/app/server.js:18:26
    at connectCallback (/usr/src/app/node_modules/mongodb/lib/mongo_client.js:314:5)
    at /usr/src/app/node_modules/mongodb/lib/mongo_client.js:233:11
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

It's probably a problem with the collection name in the URL.

**Comment by cdupont** [comment]
I think I understood the problem, the shell is interpreting the symbol `&` in the query string. Need to add quotes. Like this it works:
```
curl -S -s 'http://127.0.0.1:8080/?id=583eecac2ab79c00079d0579&colName=sth_/TEST_Sensor1_SensingDevice&dbName=sth_waziup'
```
